substitutions:
  name: piotr-voice-pe-02
  friendly_name: Piotr Voice PE 02

packages:
  piotr.voice-pe-standard: !include packages/home-assistant-voice-pe-piotr-standard.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret voice_pe_02_api_key

ota:
  - platform: esphome
    password: !secret voice_pe_02_ota_password
